# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hoang Do Express
email: admin@hoangdoexpress.com.au
description: >- # this means to ignore newlines until "baseurl:"
  Hoang Do Express - People Moving Airport Specialist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hoangdoexpress.com.au" # the base hostname & protocol for your site, e.g. http://example.com
facebook: https://www.facebook.com/hoang.do.96558061
download_appstore: https://itunes.apple.com/us/app/hoang-do-express-rider/id1380133804?ls=1&amp;mt=8
download_googleplay: https://play.google.com/store/apps/details?id=rider.droid
download_appstore_driver: https://itunes.apple.com/us/app/hoang-do-express-driver/id1380133335?ls=1&mt=8
download_googleplay_driver: https://play.google.com/store/apps/details?id=driver.droid

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
